//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GusBundle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GusBundle.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a virtual path..
        /// </summary>
        internal static string Debe_indicar_una_ruta_virtual {
            get {
                return ResourceManager.GetString("Debe_indicar_una_ruta_virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating HTTP bridge..
        /// </summary>
        internal static string Error_creando_puente_HTTP {
            get {
                return ResourceManager.GetString("Error_creando_puente_HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOR authentication failure!.
        /// </summary>
        internal static string Fallo_de_autenticación_de_TOR {
            get {
                return ResourceManager.GetString("Fallo_de_autenticación_de_TOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not found..
        /// </summary>
        internal static string No_se_encuentra_el_directorio {
            get {
                return ResourceManager.GetString("No_se_encuentra_el_directorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start server, maybe another instace is running?.
        /// </summary>
        internal static string No_se_pudo_arrancar_el_servidor_verifique_que_no_haya_otra_instancia_ejecutandose {
            get {
                return ResourceManager.GetString("No_se_pudo_arrancar_el_servidor_verifique_que_no_haya_otra_instancia_ejecutandose" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start TOR, check your internet connection..
        /// </summary>
        internal static string No_se_pudo_iniciar_TOR_verifica_tu_conexión_a_Internet {
            get {
                return ResourceManager.GetString("No_se_pudo_iniciar_TOR_verifica_tu_conexión_a_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get new identity, try again later..
        /// </summary>
        internal static string No_se_pudo_obtener_una_nueva_identidad_reitnentelo_en_unos_minutos {
            get {
                return ResourceManager.GetString("No_se_pudo_obtener_una_nueva_identidad_reitnentelo_en_unos_minutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register TOR service, your server will be inaccessible..
        /// </summary>
        internal static string No_se_pudo_registrar_el_servicio_de_TOR_no_se_podrá_acceder_a_tu_servidor {
            get {
                return ResourceManager.GetString("No_se_pudo_registrar_el_servicio_de_TOR_no_se_podrá_acceder_a_tu_servidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a path..
        /// </summary>
        internal static string Seleccione_un_directorio {
            get {
                return ResourceManager.GetString("Seleccione_un_directorio", resourceCulture);
            }
        }
    }
}
